#!/usr/bin/env bash
#
# scripts/tf-local-backend.sh -- review the Terraform without AWS credentials.
#
#   ./scripts/tf-local-backend.sh dev
#   cd infra/envs/dev && terraform init && terraform validate
#   ./scripts/tf-local-backend.sh dev --remove
#
# Both environments declare an S3 backend, so a plain `terraform init` tries to
# reach a bucket you almost certainly cannot see. Rather than commenting the
# backend out (and shipping a repo that does not show how state is configured),
# this drops a Terraform *override file* next to it. Override files replace the
# matching block at load time, so the S3 backend becomes a local one without a
# single character of the committed configuration changing.
#
# local_override.tf is gitignored -- it cannot be committed by accident.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENVIRONMENT="${1:-}"
ACTION="${2:-add}"

if [ -z "$ENVIRONMENT" ] || [ ! -d "$REPO_ROOT/infra/envs/$ENVIRONMENT" ]; then
    echo "usage: scripts/tf-local-backend.sh <dev|prod> [--remove]" >&2
    exit 1
fi

target="$REPO_ROOT/infra/envs/$ENVIRONMENT/local_override.tf"

if [ "$ACTION" = "--remove" ]; then
    rm -f "$target"
    rm -rf "$REPO_ROOT/infra/envs/$ENVIRONMENT/.terraform"
    echo "removed local backend override for '$ENVIRONMENT'" >&2
    exit 0
fi

cat > "$target" <<'HCL'
# Generated by scripts/tf-local-backend.sh -- not committed.
# Overrides the S3 backend in backend.tf so init/validate/plan work locally.
terraform {
  backend "local" {}
}
HCL

echo "wrote $target" >&2
echo "now run: cd infra/envs/$ENVIRONMENT && terraform init && terraform validate" >&2
